--LAB 1
--a
DESCRIBE EMPLOYEES;

--c
SELECT * FROM EMPLOYEES;

--e
SELECT EMPLOYEE_ID, FIRST_NAME || ' ' || LAST_NAME AS NAME, JOB_ID, HIRE_DATE
FROM EMPLOYEES;

--f
SELECT LAST_NAME || ', ' || JOB_ID AS "Angajat si titlu"
FROM EMPLOYEES;

--g
SELECT EMPLOYEE_ID || ',' || FIRST_NAME || ',' || LAST_NAME || ',' || EMAIL || ',' || PHONE_NUMBER || ',' || HIRE_DATE || ',' || JOB_ID || ',' || SALARY || ',' || COMMISSION_PCT || ',' || MANAGER_ID || ',' || DEPARTMENT_ID AS "Informatii complete"
FROM EMPLOYEES;

--h
SELECT TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI')
FROM DUAL;

--j
SELECT EMPLOYEE_ID, LAST_NAME, TO_CHAR(HIRE_DATE, 'DAY') AS "DAY HIRED"
FROM EMPLOYEES;

--k
SELECT *
FROM EMPLOYEES
ORDER BY TO_CHAR(HIRE_DATE, 'YYYY'), TO_CHAR(HIRE_DATE, 'DDD');

--l
SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > 2850
ORDER BY SALARY;

--m
SELECT LAST_NAME, JOB_ID, HIRE_DATE
FROM EMPLOYEES
WHERE
    HIRE_DATE > TO_DATE('20-FEB-87')
    AND HIRE_DATE < TO_DATE('01-MAY-89');

--n
SELECT FIRST_NAME || ' ' || LAST_NAME AS NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (10, 30, 50)
ORDER BY LAST_NAME;

--o
SELECT LAST_NAME, JOB_ID, SALARY
FROM EMPLOYEES
WHERE
    (
        JOB_ID LIKE '%CLERK%'
        OR JOB_ID LIKE '%REP%'
    )
    AND SALARY NOT IN (1000, 2000, 3000);
 
--p  
SELECT LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE MANAGER_ID IS NULL;

--q
SELECT LAST_NAME, SALARY, COMMISSION_PCT
FROM EMPLOYEES
WHERE SALARY > (SALARY * COMMISSION_PCT) * 5;
