-- LAB 2
-- 1
SELECT CONCAT(CONCAT(LAST_NAME, ' '), FIRST_NAME) || ' castiga ' || SALARY || ' lunar dar doreste ' || SALARY * 3 || '.' AS "Salariul ideal"
FROM EMPLOYEES;

--2
SELECT INITCAP(FIRST_NAME) AS PRENUME, UPPER(LAST_NAME) AS NUME, LENGTH(FIRST_NAME || LAST_NAME) AS LUNGIME_NUME
FROM EMPLOYEES
WHERE
    LAST_NAME LIKE 'M%'
    OR LAST_NAME LIKE 'J%'
    OR LAST_NAME LIKE '__a%'
ORDER BY LUNGIME_NUME DESC;

SELECT INITCAP(FIRST_NAME) AS PRENUME, UPPER(LAST_NAME) AS NUME, LENGTH(FIRST_NAME || LAST_NAME) AS LUNGIME_NUME
FROM EMPLOYEES
WHERE
    SUBSTR(LAST_NAME, 1, 1) = 'M'
    OR SUBSTR(LAST_NAME, 1, 1) = 'J'
    OR SUBSTR(LAST_NAME, 3, 1) = 'a'
ORDER BY LUNGIME_NUME DESC;

--3
SELECT EMPLOYEE_ID, LAST_NAME
FROM EMPLOYEES
WHERE INITCAP(TRIM(BOTH ' ' FROM FIRST_NAME)) = 'Steven';

--4
SELECT EMPLOYEE_ID AS ID, LAST_NAME || ' ' || FIRST_NAME AS NAME, LENGTH(FIRST_NAME || LAST_NAME) AS LUNGIME, INSTR(LAST_NAME, 'a', 1) AS PRIMA_APARITIE
FROM EMPLOYEES
WHERE LAST_NAME LIKE '%e';

--5
SELECT *
FROM EMPLOYEES
WHERE MOD(ROUND(SYSDATE-HIRE_DATE), 7) = 0;

SELECT *
FROM EMPLOYEES
WHERE TO_CHAR(SYSDATE, 'DAY') = TO_CHAR(HIRE_DATE, 'DAY');

--6
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, ROUND(SALARY*1.15, 2) "Salariu nou", ROUND(SALARY*1.15/100, 2) "Numar sute"
FROM EMPLOYEES
WHERE MOD(SALARY, 1000) != 0;

--7
SELECT LAST_NAME "Nume angajat", RPAD(HIRE_DATE, 20) "Data angajarii"
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL;

--8
SELECT TO_CHAR(SYSDATE + 30, 'MONTH DD YYYY HH24:MI:SS') "Data"
FROM DUAL;

--9
SELECT (TO_DATE('31-DEC-' || TO_CHAR(SYSDATE, 'YYYY')) - TRUNC(SYSDATE)) "Zile pana la finalul anului"
FROM DUAL;

--10a
SELECT TO_CHAR(SYSDATE + 0.5, 'DD/MM/YYYY HH24:MI:SS') "Data peste 12 ore"
FROM DUAL;

--10b
SELECT TO_CHAR(SYSDATE + 5/60/24, 'DD/MM/YYYY HH24:MI:SS') "Data peste 5 minute"
FROM DUAL;

--11
SELECT LAST_NAME || ' ' || FIRST_NAME "Nume", HIRE_DATE, NEXT_DAY(ADD_MONTHS(HIRE_DATE, 6), 'Monday') "Negociere"
FROM EMPLOYEES;

--12
SELECT LAST_NAME, ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE), 0) "Luni lucrate"
FROM EMPLOYEES
ORDER BY "Luni lucrate";

--13
SELECT LAST_NAME, HIRE_DATE, TO_CHAR(HIRE_DATE, 'DAY') "Zi"
FROM EMPLOYEES
ORDER BY DECODE(TO_CHAR(HIRE_DATE, 'D'), 1, 7, TO_CHAR(HIRE_DATE, 'D') - 1);

--14
SELECT LAST_NAME, NVL(TO_CHAR(COMMISSION_PCT), 'Fara comision') "Comision"
FROM EMPLOYEES;

SELECT LAST_NAME, DECODE(COMMISSION_PCT, NULL, 'Fara comision', COMMISSION_PCT) "Comision"
FROM EMPLOYEES;

--15
SELECT LAST_NAME, SALARY, COMMISSION_PCT
FROM EMPLOYEES
WHERE SALARY + SALARY * NVL(COMMISSION_PCT, 0) > 10000;

--16
SELECT LAST_NAME, JOB_ID, SALARY,
    DECODE(JOB_ID,
            'IT_PROG', SALARY * 1.2,
            'SA_REP', SALARY * 1.25,
            'SA_MAN', SALARY * 1.35,
            SALARY) "Salariu renegociat"
FROM EMPLOYEES;

SELECT LAST_NAME, JOB_ID, SALARY,
    CASE JOB_ID
    WHEN 'IT_PROG' THEN SALARY * 1.2
    WHEN 'SA_REP' THEN SALARY * 1.25
    WHEN 'SA_MAN' THEN SALARY * 1.35
    ELSE SALARY
    END "Salariu renegociat"
FROM EMPLOYEES;

--17
SELECT E.LAST_NAME, E.EMPLOYEE_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;

--18
SELECT DISTINCT J.JOB_ID, J.JOB_TITLE
FROM EMPLOYEES E, JOBS J
WHERE
    E.DEPARTMENT_ID = 30
    AND E.JOB_ID=J.JOB_ID;
    
--19
SELECT E.LAST_NAME, D.DEPARTMENT_NAME, L.CITY
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L
WHERE 
    E.COMMISSION_PCT IS NOT NULL
    AND E.DEPARTMENT_ID=D.DEPARTMENT_ID
    AND D.LOCATION_ID=L.LOCATION_ID;
    
--20
SELECT E.LAST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE
    LOWER(E.LAST_NAME) LIKE '%a%'
    AND E.DEPARTMENT_ID=D.DEPARTMENT_ID;
    
--21
SELECT E.LAST_NAME, J.JOB_TITLE, D.DEPARTMENT_NAME
FROM EMPLOYEES E, JOBS J, DEPARTMENTS D, LOCATIONS L
WHERE
    L.CITY = 'Oxford'
    AND E.JOB_ID=J.JOB_ID
    AND E.DEPARTMENT_ID=D.DEPARTMENT_ID
    AND D.LOCATION_ID = L.LOCATION_ID;
    
--22
SELECT
    E.EMPLOYEE_ID Ang#, E.LAST_NAME Angajat,
    M.EMPLOYEE_ID Mgr#, M.LAST_NAME Manager
FROM EMPLOYEES E, EMPLOYEES M
WHERE E.MANAGER_ID=M.EMPLOYEE_ID;

--23 - V1
SELECT
    E.EMPLOYEE_ID Ang#, E.LAST_NAME Angajat,
    M.EMPLOYEE_ID Mgr#, M.LAST_NAME Manager
FROM EMPLOYEES E, EMPLOYEES M
WHERE E.MANAGER_ID=M.EMPLOYEE_ID(+);

--23 - V2

SELECT
    E.EMPLOYEE_ID Ang#, E.LAST_NAME Angajat,
    M.EMPLOYEE_ID Mgr#, M.LAST_NAME Manager
FROM EMPLOYEES E
LEFT JOIN EMPLOYEES M
ON E.MANAGER_ID = M.EMPLOYEE_ID;


--24
SELECT E.LAST_NAME NUME, E.DEPARTMENT_ID, C.LAST_NAME NUME_COLEG
FROM EMPLOYEES E, EMPLOYEES C
WHERE E.DEPARTMENT_ID = C.DEPARTMENT_ID AND E.EMPLOYEE_ID<>C.EMPLOYEE_ID;

--25
SELECT E.LAST_NAME, J.JOB_ID, J.JOB_TITLE, D.DEPARTMENT_NAME, E.SALARY, D.DEPARTMENT_ID
FROM EMPLOYEES E, JOBS J, DEPARTMENTS D
WHERE
    E.JOB_ID=J.JOB_ID
    AND E.DEPARTMENT_ID=D.DEPARTMENT_ID(+);
    
--26
SELECT E.LAST_NAME, E.HIRE_DATE
FROM EMPLOYEES E, EMPLOYEES G
WHERE
    UPPER(G.LAST_NAME)='GATES' AND E.HIRE_DATE>G.HIRE_DATE;
    
--27
SELECT E.LAST_NAME Angajat, E.HIRE_DATE Data_ang, M.LAST_NAME Manager, M.HIRE_DATE Data_mgr
FROM EMPLOYEES E, EMPLOYEES M
WHERE
    E.MANAGER_ID=M.EMPLOYEE_ID
    AND E.HIRE_DATE<M.HIRE_DATE;
