-- LAB 3
--1
SELECT E1.LAST_NAME NUME, TO_CHAR(E1.HIRE_DATE, 'MONTH') LUNA_ANG, TO_CHAR(E1.HIRE_DATE, 'YYYY') AN_ANG
FROM EMPLOYEES E1, EMPLOYEES E2
WHERE
    UPPER(E2.LAST_NAME) = 'GATES'
    AND E1.DEPARTMENT_ID = E2.DEPARTMENT_ID
    AND UPPER(E1.LAST_NAME) LIKE '%A%'
    AND UPPER(E1.LAST_NAME) <> 'GATES';
    
SELECT E1.LAST_NAME NUME, TO_CHAR(E1.HIRE_DATE, 'MONTH') LUNA_ANG, TO_CHAR(E1.HIRE_DATE, 'YYYY') AN_ANG
FROM EMPLOYEES E1
JOIN EMPLOYEES E2 USING (DEPARTMENT_ID)
WHERE
    UPPER(E2.LAST_NAME) = 'GATES'
    AND INSTR(UPPER(E1.LAST_NAME), 'A') <> 0
    AND UPPER(E1.LAST_NAME) <> 'GATES';

--2
SELECT UNIQUE E1.EMPLOYEE_ID, E1.LAST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E1, EMPLOYEES E2, DEPARTMENTS D
WHERE
    UPPER(E2.LAST_NAME) LIKE '%T%'
    AND E1.DEPARTMENT_ID = E2.DEPARTMENT_ID
    AND E1.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY 2;

SELECT UNIQUE E1.EMPLOYEE_ID, E1.LAST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E1 JOIN EMPLOYEES E2 ON (E1.DEPARTMENT_ID = E2.DEPARTMENT_ID)
                JOIN DEPARTMENTS D ON (E1.DEPARTMENT_ID = D.DEPARTMENT_ID)
WHERE UPPER(E2.LAST_NAME) LIKE '%T%'
ORDER BY 2;

SELECT UNIQUE E.EMPLOYEE_ID, E.LAST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE
    E.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE UPPER(LAST_NAME) LIKE '%T%')
    AND E.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY 2;

--3
SELECT E1.LAST_NAME, E1.SALARY, J.JOB_TITLE, L.CITY, C.COUNTRY_NAME
FROM EMPLOYEES E1, EMPLOYEES E2, JOBS J, LOCATIONS L, COUNTRIES C, DEPARTMENTS D
WHERE
    UPPER(E2.LAST_NAME) = 'KING'
    AND E1.MANAGER_ID = E2.EMPLOYEE_ID
    AND E1.JOB_ID = J.JOB_ID
    AND E1.DEPARTMENT_ID = D.DEPARTMENT_ID
    AND D.LOCATION_ID = L.LOCATION_ID
    AND L.COUNTRY_ID = C.COUNTRY_ID;
    
SELECT E1.LAST_NAME, E1.SALARY, J.JOB_TITLE, L.CITY, C.COUNTRY_NAME
FROM EMPLOYEES E1 JOIN EMPLOYEES E2 ON (E1.MANAGER_ID = E2.EMPLOYEE_ID)
                JOIN JOBS J ON (E1.JOB_ID = J.JOB_ID)
                JOIN DEPARTMENTS D ON (E1.DEPARTMENT_ID = D.DEPARTMENT_ID)
                JOIN LOCATIONS L ON (D.LOCATION_ID = L.LOCATION_ID)
                JOIN COUNTRIES C ON (L.COUNTRY_ID = C.COUNTRY_ID)
WHERE UPPER(E2.LAST_NAME) = 'KING';
    
SELECT E.LAST_NAME, E.SALARY, J.JOB_TITLE, L.CITY, C.COUNTRY_NAME
FROM EMPLOYEES E, JOBS J, LOCATIONS L, COUNTRIES C, DEPARTMENTS D
WHERE
    E.MANAGER_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE UPPER(LAST_NAME) = 'KING')
    AND E.JOB_ID = J.JOB_ID
    AND E.DEPARTMENT_ID = D.DEPARTMENT_ID
    AND D.LOCATION_ID = L.LOCATION_ID
    AND L.COUNTRY_ID = C.COUNTRY_ID;
    
--4