-- LAB 6
--2 (24000 2100 691400 6462)
SELECT MAX(SALARY) Maxim, MIN(SALARY) Minim, SUM(SALARY) Suma, ROUND(AVG(SALARY)) Media
FROM EMPLOYEES;

--3 (19 REZULTATE)
SELECT JOB_ID, MAX(SALARY) Maxim, MIN(SALARY) Minim, SUM(SALARY) Suma, ROUND(AVG(SALARY)) Media
FROM EMPLOYEES
GROUP BY JOB_ID;

--4 (19 REZULTATE)
SELECT JOB_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY JOB_ID;

--5 (18)
SELECT COUNT(DISTINCT MANAGER_ID) "Nr. manageri"
FROM EMPLOYEES;

--6 (21900)
SELECT MAX(SALARY) - MIN(SALARY) "Diferenta"
FROM EMPLOYEES;

--7 (11 REZULTATE)
SELECT D.DEPARTMENT_NAME DEPARTAMENT, L.CITY LOCATIE, COUNT(*) NR_ANG, ROUND(AVG(E.SALARY)) SALARIU_MEDIU
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L
WHERE
    E.DEPARTMENT_ID = D.DEPARTMENT_ID
    AND D.LOCATION_ID = L.LOCATION_ID
GROUP BY D.DEPARTMENT_NAME, L.CITY;

--8 (51 REZULTATE)
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY)
                FROM EMPLOYEES)
ORDER BY SALARY DESC;

--9 (4 REZULTATE)
SELECT MANAGER_ID, MIN(SALARY)
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL
GROUP BY MANAGER_ID
HAVING MIN(SALARY) >= 7000
ORDER BY 2 DESC;

--10 (9 REZULTATE)
SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, MAX(E.SALARY)
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME
HAVING MAX(E.SALARY) > 7000;

--11 (2780)
SELECT MIN(AVG(SALARY))
FROM EMPLOYEES
GROUP BY JOB_ID;

--12 (11 REZULTATE)
SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, ROUND(AVG(E.SALARY))
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME;

--13 (19333)
SELECT MAX(ROUND(AVG(SALARY)))
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

--14 (PU_CLERK	Purchasing Clerk	2780)
SELECT J.JOB_ID, J.JOB_TITLE, ROUND(AVG(E.SALARY))
FROM EMPLOYEES E, JOBS J
WHERE E.JOB_ID = J.JOB_ID
GROUP BY J.JOB_ID, J.JOB_TITLE
HAVING ROUND(AVG(E.SALARY)) = (SELECT MIN(ROUND(AVG(SALARY)))
                                FROM EMPLOYEES
                                GROUP BY JOB_ID);
                                
--15 (6462)
SELECT ROUND(AVG(SALARY))
FROM EMPLOYEES
HAVING ROUND(AVG(SALARY)) > 2500;

--16 (20 REZULTATE)
SELECT DEPARTMENT_ID, JOB_ID, SUM(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, JOB_ID;

SELECT D.DEPARTMENT_NAME, J.JOB_TITLE, SUM(SALARY)
FROM EMPLOYEES E, DEPARTMENTS D, JOBS J
WHERE
    E.DEPARTMENT_ID = D.DEPARTMENT_ID(+)
    AND E.JOB_ID = J.JOB_ID
GROUP BY D.DEPARTMENT_NAME, J.JOB_TITLE;

--17 (Executive	17000)
SELECT D.DEPARTMENT_NAME, MIN(E.SALARY)
FROM DEPARTMENTS D, EMPLOYEES E
WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME
HAVING AVG(SALARY) = (SELECT MAX(AVG(SALARY))
                        FROM EMPLOYEES
                        GROUP BY DEPARTMENT_ID);
                        
--18
--a (6 REZULTATE)
SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, COUNT(*)
FROM DEPARTMENTS D, EMPLOYEES E
WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME
HAVING COUNT(*) < 4;

--b (50	Shipping	45)
SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, COUNT(*)
FROM DEPARTMENTS D, EMPLOYEES E
WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME
HAVING COUNT(*) = (SELECT MAX(COUNT(*))
                    FROM EMPLOYEES
                    GROUP BY DEPARTMENT_ID);
                    
--19 (12 REZULTATE)
SELECT *
FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE, 'DD') IN (SELECT TO_CHAR(HIRE_DATE, 'DD')
                                    FROM EMPLOYEES
                                    GROUP BY TO_CHAR(HIRE_DATE, 'DD')
                                    HAVING COUNT(*) = (SELECT MAX(COUNT(*))
                                                        FROM EMPLOYEES
                                                        GROUP BY TO_CHAR(HIRE_DATE, 'DD')));

--20 (2)
SELECT COUNT(COUNT(*))
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) > 15;

--21 (2 REZULTATE)
SELECT DEPARTMENT_ID, SUM(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID <> 30
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) > 10
ORDER BY 2 ASC;

--22 (122 REZULTATE)
SELECT AUX.*, E.LAST_NAME, E.SALARY, E.JOB_ID
FROM EMPLOYEES E, (SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, COUNT(E.EMPLOYEE_ID), ROUND(AVG(E.SALARY))
                    FROM EMPLOYEES E, DEPARTMENTS D
                    WHERE E.DEPARTMENT_ID(+) = D.DEPARTMENT_ID
                    GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME) AUX
WHERE E.DEPARTMENT_ID(+) = AUX.DEPARTMENT_ID;

--23 (6 REZULTATE)
SELECT L.CITY ORAS, D.DEPARTMENT_NAME DEPARTAMENT, E.JOB_ID JOB, SUM(E.SALARY) SALARIU
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L
WHERE
    E.DEPARTMENT_ID = D.DEPARTMENT_ID
    AND D.LOCATION_ID = L.LOCATION_ID
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME, E.JOB_ID, L.CITY
HAVING D.DEPARTMENT_ID > 80;

--24 (3 REZULTATE)
SELECT EMPLOYEE_ID, LAST_NAME, FIRST_NAME
FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (SELECT EMPLOYEE_ID
                        FROM JOB_HISTORY
                        GROUP BY EMPLOYEE_ID
                        HAVING COUNT(*) >= 2);

--25 (0.072897196261682242990654205607476635514)
SELECT AVG(AUX.COMISION)
FROM (SELECT NVL(COMMISSION_PCT, 0) COMISION FROM EMPLOYEES) AUX;