-- LAB 7
-- I (24000)
SELECT MAX(SALARY) SAL_MAX
FROM EMPLOYEES
HAVING MAX(SALARY) > 15000;

-- II (100	King Steven	Executive	Seattle)
SELECT
    E.EMPLOYEE_ID ID_ANG,
    E.LAST_NAME || ' ' || E.FIRST_NAME NUME_ANG,
    D.DEPARTMENT_NAME NUME_DEP,
    L.CITY ORAS
FROM
    EMPLOYEES E,
    DEPARTMENTS D,
    LOCATIONS L
WHERE
    E.DEPARTMENT_ID = D.DEPARTMENT_ID
    AND D.LOCATION_ID = L.LOCATION_ID
    AND E.SALARY = (SELECT MAX(SALARY) SAL_MAX
                    FROM EMPLOYEES
                    HAVING MAX(SALARY) > 15000);
                    
-- III (16 REZULTATE)
SELECT
    E.LAST_NAME || ' ' || E.FIRST_NAME NUME_ANG,
    E.HIRE_DATE DATA_ANG
FROM EMPLOYEES E
WHERE 
    E.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                        FROM EMPLOYEES
                        GROUP BY DEPARTMENT_ID
                        HAVING COUNT(*) > 8)
    AND E.HIRE_DATE > (SELECT MAX(HIRE_DATE)
                        FROM EMPLOYEES
                        WHERE DEPARTMENT_ID = 30);
                        
-- 1 (11 REZULTATE)
SELECT
    D.DEPARTMENT_ID ID_DEP,
    D.DEPARTMENT_NAME NUME_DEP,
    AUX.SUMA SUMA_SAL
FROM
    DEPARTMENTS D,
    (SELECT
        SUM(SALARY) SUMA,
        DEPARTMENT_ID
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID) AUX
WHERE D.DEPARTMENT_ID = AUX.DEPARTMENT_ID;

-- 2
SELECT
    E.LAST_NAME NUME_ANG,
    E.SALARY,
    E.DEPARTMENT_ID,
    AUX.MEDIE_SAL
FROM
    EMPLOYEES E,
    (SELECT
        ROUND(AVG(SALARY), 2) MEDIE_SAL,
        DEPARTMENT_ID
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID) AUX
WHERE E.DEPARTMENT_ID = AUX.DEPARTMENT_ID;

-- 3
SELECT
    E.LAST_NAME NUME_ANG,
    E.SALARY,
    E.DEPARTMENT_ID,
    AUX.MEDIE_SAL,
    AUX.NR_ANG
FROM
    EMPLOYEES E,
    (SELECT
        DEPARTMENT_ID,
        ROUND(AVG(SALARY), 2) MEDIE_SAL,
        COUNT(*) NR_ANG
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID) AUX
WHERE E.DEPARTMENT_ID = AUX.DEPARTMENT_ID;

-- 4 (12 REZULTATE)
SELECT
    DEPARTMENT_ID ID_DEP,
    MIN(SALARY) SAL_MIN
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT
    D.DEPARTMENT_NAME,
    E.LAST_NAME NUME_ANG,
    E.SALARY SAL_ANG
FROM
    DEPARTMENTS D,
    EMPLOYEES E,
    (SELECT DEPARTMENT_ID, MIN(SALARY) MIN_SAL
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID) AUX
WHERE
    E.DEPARTMENT_ID = AUX.DEPARTMENT_ID
    AND E.SALARY = AUX.MIN_SAL
    AND D.DEPARTMENT_ID = E.DEPARTMENT_ID;
    
-- 5 
-- a (38 REZULTATE)
SELECT
    E.LAST_NAME NUME_ANG,
    E.SALARY SAL_ANG,
    E.DEPARTMENT_ID ID_DEP
FROM EMPLOYEES E
WHERE E.SALARY > (SELECT AVG(E2.SALARY)
                    FROM EMPLOYEES E2
                    WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID);
-- b (38 REZULTATE)
SELECT
    E.LAST_NAME NUME_ANG,
    E.SALARY SAL_ANG,
    E.DEPARTMENT_ID ID_DEP,
    D.DEPARTMENT_NAME,
    AUX.MEDIE_SAL,
    AUX.NR_ANG
FROM
    EMPLOYEES E,
    DEPARTMENTS D,
    (SELECT
        DEPARTMENT_ID,
        ROUND(AVG(SALARY), 2) MEDIE_SAL,
        COUNT(*) NR_ANG
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID) AUX   
WHERE
    E.DEPARTMENT_ID = D.DEPARTMENT_ID
    AND E.DEPARTMENT_ID = AUX.DEPARTMENT_ID
    AND E.SALARY > (SELECT AVG(E2.SALARY)
                    FROM EMPLOYEES E2
                    WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID);
    
-- 6 (King	24000)
-- VARIANTA ALL
SELECT
    E.LAST_NAME NUME_ANG,
    E.SALARY SAL_ANG
FROM EMPLOYEES E
WHERE E.SALARY > ALL(SELECT AVG(SALARY)
                        FROM EMPLOYEES
                        GROUP BY DEPARTMENT_ID);
                    
-- VARIANTA MAX
SELECT
    E.LAST_NAME NUME_ANG,
    E.SALARY SAL_ANG
FROM EMPLOYEES E
WHERE E.SALARY > (SELECT MAX(AVG(SALARY))
                    FROM EMPLOYEES
                    GROUP BY DEPARTMENT_ID);
                    
-- 7 (12 REZULTATE)
SELECT
    E.LAST_NAME NUME_ANG,
    E.SALARY SAL_ANG
FROM EMPLOYEES E
WHERE (E.DEPARTMENT_ID, E.SALARY) IN (SELECT E2.DEPARTMENT_ID, MIN(E2.SALARY)
                                        FROM EMPLOYEES E2
                                        GROUP BY E2.DEPARTMENT_ID);

-- 8 (12 REZULTATE)
SELECT
    D.DEPARTMENT_ID ID_DEP,
    D.DEPARTMENT_NAME NUME_DEP,
    E.LAST_NAME NUME_ANG
FROM
    EMPLOYEES E,
    DEPARTMENTS D
WHERE
    E.DEPARTMENT_ID = D.DEPARTMENT_ID
    AND (E.DEPARTMENT_ID, E.HIRE_DATE) IN (SELECT DEPARTMENT_ID, MIN(HIRE_DATE)
                                            FROM EMPLOYEES
                                            GROUP BY DEPARTMENT_ID)
ORDER BY 2;

-- 9 (39 REZULTATE)
SELECT E.LAST_NAME NUME_ANG
FROM EMPLOYEES E
WHERE EXISTS (SELECT 1
                FROM EMPLOYEES E2
                WHERE
                    E2.DEPARTMENT_ID = E.DEPARTMENT_ID
                    AND E2.SALARY > 12500);
        
-- 10 (40 REZULTATE)
SELECT E.LAST_NAME NUME_ANG
FROM EMPLOYEES E
WHERE EXISTS (SELECT 1
                FROM EMPLOYEES E2
                WHERE
                    E2.DEPARTMENT_ID = E.DEPARTMENT_ID
                    AND E2.SALARY = (SELECT MAX(E3.SALARY)
                                    FROM EMPLOYEES E3
                                    WHERE E3.DEPARTMENT_ID = 30));
                                    
-- 11 (16 REZULTATE)
-- V1
SELECT
    D.DEPARTMENT_ID ID_DEP,
    D.DEPARTMENT_NAME NUME_DEP
FROM DEPARTMENTS D
WHERE NOT EXISTS (SELECT 1
                    FROM EMPLOYEES E
                    WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID);
                    
-- V2
SELECT
    D.DEPARTMENT_ID ID_DEP,
    D.DEPARTMENT_NAME NUME_DEP
FROM DEPARTMENTS D
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                            FROM EMPLOYEES
                            WHERE DEPARTMENT_ID IS NOT NULL
                            GROUP BY DEPARTMENT_ID
                            HAVING COUNT(1) > 0);
                            
-- 12 (15 REZULTATE)
SELECT
    E.EMPLOYEE_ID ID_ANG,
    E.LAST_NAME || ' ' || E.FIRST_NAME NUME_ANG
FROM EMPLOYEES E
WHERE E.EMPLOYEE_ID IN (SELECT MANAGER_ID
                        FROM EMPLOYEES
                        GROUP BY MANAGER_ID
                        HAVING COUNT(1) >= 2);
                        
-- 13 (7 REZULTATE)
-- VARIANTA EXISTS
SELECT
    L.LOCATION_ID ID_LOC,
    L.CITY ORAS
FROM LOCATIONS L
WHERE EXISTS (SELECT 1
                FROM DEPARTMENTS D
                WHERE D.LOCATION_ID = L.LOCATION_ID);
                
-- VARIANTA IN
SELECT
    L.LOCATION_ID ID_LOC,
    L.CITY ORAS
FROM LOCATIONS L
WHERE L.LOCATION_ID IN (SELECT UNIQUE D.LOCATION_ID
                        FROM DEPARTMENTS D);
                        
-- 14 (testtest)
-- V1
-- JOBURILE CARE NU AU FOST OCUPATE IN TRECUT
SELECT J.JOB_TITLE NUME_JOB
FROM JOBS J
WHERE NOT EXISTS (SELECT 1
                    FROM JOB_HISTORY JH
                    WHERE JH.JOB_ID = J.JOB_ID)
INTERSECT
--JOBURILE CARE NU SUNT OCUPATE IN PREZENT
SELECT J.JOB_TITLE NUME_JOB
FROM JOBS J
WHERE NOT EXISTS (SELECT 1
                    FROM EMPLOYEES E
                    WHERE E.JOB_ID = J.JOB_ID);

-- V2   
SELECT J.JOB_TITLE NUME_JOB
FROM JOBS J
WHERE J.JOB_ID NOT IN (SELECT DISTINCT E.JOB_ID
                        FROM EMPLOYEES E
                        UNION
                        SELECT DISTINCT JH.JOB_ID
                        FROM JOB_HISTORY JH);