-- LAB 8
-- 1
WITH
SAL_DEP AS (SELECT
                D.DEPARTMENT_NAME NUME_DEP,
                SUM(E.SALARY) SAL_TOT
            FROM
                EMPLOYEES E,
                DEPARTMENTS D
            WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
            GROUP BY D.DEPARTMENT_NAME),
VAL_MED AS (SELECT AVG(SAL_TOT) MEDIE
            FROM SAL_DEP)
SELECT *
FROM SAL_DEP
WHERE SAL_DEP.SAL_TOT > (SELECT MEDIE FROM VAL_MED);

-- 2 (3 REZULTATE)
WITH
SAL_MNG AS (SELECT
                E.DEPARTMENT_ID ID_DEP,
                E.LAST_NAME NUME_MNG,
                AUX.SAL_TOT
            FROM
                EMPLOYEES E,
                (SELECT MANAGER_ID, SUM(SALARY) SAL_TOT
                 FROM EMPLOYEES
                 GROUP BY MANAGER_ID) AUX
            WHERE E.EMPLOYEE_ID = AUX.MANAGER_ID),
AVG_DEP AS (SELECT
                DEPARTMENT_ID ID_DEP,
                AVG(SALARY) MEDIE_SAL
            FROM EMPLOYEES
            GROUP BY DEPARTMENT_ID)
SELECT NUME_MNG, SAL_TOT
FROM SAL_MNG
WHERE SAL_TOT < (SELECT AVG_DEP.MEDIE_SAL
                 FROM AVG_DEP
                 WHERE AVG_DEP.ID_DEP = SAL_MNG.ID_DEP);
                
-- 3 (10 REZULTATE)
SELECT *
FROM (SELECT *
      FROM EMPLOYEES
    ORDER BY SALARY DESC)
WHERE ROWNUM <= 10;

-- 4 (3 REZULTATE)
SELECT *
FROM (SELECT
        JOB_ID ID_JOB,
        JOB_TITLE NUME_JOB,
        ((MAX_SALARY + MIN_SALARY) / 2) MEDIE
      FROM JOBS
      ORDER BY 3)
WHERE ROWNUM <= 3;

-- 5 (4 REZULTATE)
WITH
ANG_PER_DEP AS (SELECT
                    D.DEPARTMENT_NAME NUME_DEP,
                    AUX.NR_ANG
                FROM
                    DEPARTMENTS D,
                    (SELECT DEPARTMENT_ID, COUNT(1) NR_ANG
                     FROM EMPLOYEES
                     GROUP BY DEPARTMENT_ID) AUX
                WHERE D.DEPARTMENT_ID = AUX.DEPARTMENT_ID
                ORDER BY 2 DESC)
SELECT *
FROM ANG_PER_DEP
WHERE ROWNUM <= 4;

-- 6 (27 REZULTATE)
SELECT
    'Departamentul ' || D.DEPARTMENT_NAME ||
    ' este condus de ' || NVL(TO_CHAR(D.MANAGER_ID), 'nimeni') || ' si '||
    NVL2(AUX.NR_ANG, 'are numarul de salariati ' || AUX.NR_ANG, 'nu are salariati') DESC_DEPT
FROM
    DEPARTMENTS D,
    (SELECT DEPARTMENT_ID, COUNT(1) NR_ANG
     FROM EMPLOYEES
     GROUP BY DEPARTMENT_ID) AUX
WHERE D.DEPARTMENT_ID = AUX.DEPARTMENT_ID(+);

-- 7 (107 REZULTATE)
SELECT
    LAST_NAME NUME,
    FIRST_NAME PRENUME,
    NULLIF(LENGTH(LAST_NAME), LENGTH(FIRST_NAME)) LUNGIME_NUME
FROM EMPLOYEES;

-- 8 (107 REZULTATE)
-- VARIANTA CASE
SELECT
    E.LAST_NAME || ' ' || E.FIRST_NAME NUME_ANG,
    E.HIRE_DATE DATA_ANG,
    E.SALARY SAL_ANG,
    CASE TO_CHAR(E.HIRE_DATE, 'YYYY')
        WHEN '1989' THEN E.SALARY * 1.2
        WHEN '1990' THEN E.SALARY * 1.15
        WHEN '1991' THEN E.SALARY * 1.1
        ELSE E.SALARY
    END SAL_MAJ
FROM EMPLOYEES E;

-- VARIANTA DECODE
SELECT
    E.LAST_NAME || ' ' || E.FIRST_NAME NUME_ANG,
    E.HIRE_DATE DATA_ANG,
    E.SALARY SAL_ANG,
    DECODE(TO_CHAR(E.HIRE_DATE, 'YYYY'),
           '1989', E.SALARY * 1.2,
           '1990', E.SALARY * 1.15,
           '1991', E.SALARY * 1.1,
           E.SALARY) SAL_MAJ
FROM EMPLOYEES E;

-- 9 (19 REZULTATE)
WITH JOB_SAL_MAX AS (SELECT JOB_ID
                     FROM EMPLOYEES
                     WHERE SALARY = (SELECT MAX(SALARY)
                                     FROM EMPLOYEES))
SELECT
    JOB_ID,
    CASE
        WHEN UPPER(AUX.JOB_ID) LIKE 'S%' THEN AUX.SUMA_SAL
        WHEN AUX.JOB_ID = (SELECT JOB_ID FROM JOB_SAL_MAX) THEN AUX.AVG_SAL
        ELSE AUX.MIN_SAL
    END REZ
FROM (SELECT
        JOB_ID,
        SUM(SALARY) SUMA_SAL,
        AVG(SALARY) AVG_SAL,
        MIN(SALARY) MIN_SAL
      FROM EMPLOYEES
      GROUP BY JOB_ID) AUX;

-- 10 (19 REZULTATE)
-- (NVL, SUM, DECODE)
SELECT
    JOB_ID ID_JOB,
    NVL(SUM(DECODE(DEPARTMENT_ID, 30, SALARY)), 0) DEP30,
    NVL(SUM(DECODE(DEPARTMENT_ID, 50, SALARY)), 0) DEP50,
    NVL(SUM(DECODE(DEPARTMENT_ID, 0, SALARY)), 0) DEP80,
    NVL(SUM(SALARY), 0) TOTAL
FROM EMPLOYEES
GROUP BY JOB_ID;

-- (SUBCERERI CORELATE IN SELECT)
SELECT
    E.JOB_ID ID_JOB,
    (SELECT NVL(SUM(SALARY), 0)
     FROM EMPLOYEES
     WHERE
        JOB_ID = E.JOB_ID
        AND DEPARTMENT_ID = 30) DEP30,
    (SELECT NVL(SUM(SALARY), 0)
     FROM EMPLOYEES
     WHERE
        JOB_ID = E.JOB_ID
        AND DEPARTMENT_ID = 50) DEP50,
    (SELECT NVL(SUM(SALARY), 0)
     FROM EMPLOYEES
     WHERE
        JOB_ID = E.JOB_ID
        AND DEPARTMENT_ID = 80) DEP80
FROM EMPLOYEES E
GROUP BY E.JOB_ID;

-- 11 (107	28	23	18	11)
-- (NVL, SUM, DECODE)
SELECT
    COUNT(1) NR_ANG_TOTAL,
    NVL(SUM(DECODE(TO_CHAR(HIRE_DATE, 'YYYY'), '1997', 1, 0)), 0) NR_ANG_1997,
    NVL(SUM(DECODE(TO_CHAR(HIRE_DATE, 'YYYY'), '1998', 1, 0)), 0) NR_ANG_1998,
    NVL(SUM(DECODE(TO_CHAR(HIRE_DATE, 'YYYY'), '1999', 1, 0)), 0) NR_ANG_1999,
    NVL(SUM(DECODE(TO_CHAR(HIRE_DATE, 'YYYY'), '2000', 1, 0)), 0) NR_ANG_2000
FROM EMPLOYEES;

-- (SUBCERERI CORELATE IN SELECT)
SELECT
    (SELECT NVL(COUNT(1), 0)
     FROM EMPLOYEES) NR_ANG_TOTAL,
    (SELECT NVL(COUNT(1), 0)
     FROM EMPLOYEES
     WHERE TO_CHAR(HIRE_DATE, 'YYYY') = '1997') NR_ANG_1997,
    (SELECT NVL(COUNT(1), 0)
     FROM EMPLOYEES
     WHERE TO_CHAR(HIRE_DATE, 'YYYY') = '1998') NR_ANG_1998,
    (SELECT NVL(COUNT(1), 0)
     FROM EMPLOYEES
     WHERE TO_CHAR(HIRE_DATE, 'YYYY') = '1999') NR_ANG_1999,
    (SELECT NVL(COUNT(1), 0)
     FROM EMPLOYEES
     WHERE TO_CHAR(HIRE_DATE, 'YYYY') = '2000') NR_ANG_2000
FROM DUAL;